install_data(
  'backup.py',
  'components.py',
  'config_manager.py',
  'ea_fix.py',
  'gamepad.py',
  'hv_client.py',
  'hv_manager.py',
  'identity.py',
  'keyboard.py',
  'language_config.py',
  'launcher.py',
  'migration.py',
  'path_manager.py',
  'proton_downloader.py',
  'proton_manager.py',
  'runner.py',
  'shortcut.py',
  'steam_setup.py',
  'tray_sni.py',
  'utils.py',
  install_dir: get_option('libdir') / 'uwu-launcher' / 'faugus',
)
