install_data(
  'uwu-launcher-raster.png',
  'faugus-notification.ogg',
  'gamecontrollerdb.txt',
)

install_data(
  'uwu-add-symbolic.svg',
  'uwu-kill-symbolic.svg',
  'uwu-play-symbolic.svg',
  'uwu-settings-symbolic.svg',
  'uwu-stop-symbolic.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'actions',
)

install_data(
  'uwu-launcher.svg',
  'uwu-mono.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'apps',
)

install_data(
  'uwu-launcher.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'apps',
  rename: 'io.github.xXJSONDeruloXx.uwu-launcher.svg',
)
